/*
Akeyless API

The purpose of this application is to provide access to Akeyless API.

API version: 2.0
Contact: support@akeyless.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package akeyless

import (
	"encoding/json"
)

// checks if the SplunkLogForwardingConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SplunkLogForwardingConfig{}

// SplunkLogForwardingConfig struct for SplunkLogForwardingConfig
type SplunkLogForwardingConfig struct {
	SplunkIndex *string `json:"splunk_index,omitempty"`
	SplunkSource *string `json:"splunk_source,omitempty"`
	SplunkSourcetype *string `json:"splunk_sourcetype,omitempty"`
	SplunkToken *string `json:"splunk_token,omitempty"`
	SplunkUrl *string `json:"splunk_url,omitempty"`
}

// NewSplunkLogForwardingConfig instantiates a new SplunkLogForwardingConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSplunkLogForwardingConfig() *SplunkLogForwardingConfig {
	this := SplunkLogForwardingConfig{}
	return &this
}

// NewSplunkLogForwardingConfigWithDefaults instantiates a new SplunkLogForwardingConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSplunkLogForwardingConfigWithDefaults() *SplunkLogForwardingConfig {
	this := SplunkLogForwardingConfig{}
	return &this
}

// GetSplunkIndex returns the SplunkIndex field value if set, zero value otherwise.
func (o *SplunkLogForwardingConfig) GetSplunkIndex() string {
	if o == nil || IsNil(o.SplunkIndex) {
		var ret string
		return ret
	}
	return *o.SplunkIndex
}

// GetSplunkIndexOk returns a tuple with the SplunkIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SplunkLogForwardingConfig) GetSplunkIndexOk() (*string, bool) {
	if o == nil || IsNil(o.SplunkIndex) {
		return nil, false
	}
	return o.SplunkIndex, true
}

// HasSplunkIndex returns a boolean if a field has been set.
func (o *SplunkLogForwardingConfig) HasSplunkIndex() bool {
	if o != nil && !IsNil(o.SplunkIndex) {
		return true
	}

	return false
}

// SetSplunkIndex gets a reference to the given string and assigns it to the SplunkIndex field.
func (o *SplunkLogForwardingConfig) SetSplunkIndex(v string) {
	o.SplunkIndex = &v
}

// GetSplunkSource returns the SplunkSource field value if set, zero value otherwise.
func (o *SplunkLogForwardingConfig) GetSplunkSource() string {
	if o == nil || IsNil(o.SplunkSource) {
		var ret string
		return ret
	}
	return *o.SplunkSource
}

// GetSplunkSourceOk returns a tuple with the SplunkSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SplunkLogForwardingConfig) GetSplunkSourceOk() (*string, bool) {
	if o == nil || IsNil(o.SplunkSource) {
		return nil, false
	}
	return o.SplunkSource, true
}

// HasSplunkSource returns a boolean if a field has been set.
func (o *SplunkLogForwardingConfig) HasSplunkSource() bool {
	if o != nil && !IsNil(o.SplunkSource) {
		return true
	}

	return false
}

// SetSplunkSource gets a reference to the given string and assigns it to the SplunkSource field.
func (o *SplunkLogForwardingConfig) SetSplunkSource(v string) {
	o.SplunkSource = &v
}

// GetSplunkSourcetype returns the SplunkSourcetype field value if set, zero value otherwise.
func (o *SplunkLogForwardingConfig) GetSplunkSourcetype() string {
	if o == nil || IsNil(o.SplunkSourcetype) {
		var ret string
		return ret
	}
	return *o.SplunkSourcetype
}

// GetSplunkSourcetypeOk returns a tuple with the SplunkSourcetype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SplunkLogForwardingConfig) GetSplunkSourcetypeOk() (*string, bool) {
	if o == nil || IsNil(o.SplunkSourcetype) {
		return nil, false
	}
	return o.SplunkSourcetype, true
}

// HasSplunkSourcetype returns a boolean if a field has been set.
func (o *SplunkLogForwardingConfig) HasSplunkSourcetype() bool {
	if o != nil && !IsNil(o.SplunkSourcetype) {
		return true
	}

	return false
}

// SetSplunkSourcetype gets a reference to the given string and assigns it to the SplunkSourcetype field.
func (o *SplunkLogForwardingConfig) SetSplunkSourcetype(v string) {
	o.SplunkSourcetype = &v
}

// GetSplunkToken returns the SplunkToken field value if set, zero value otherwise.
func (o *SplunkLogForwardingConfig) GetSplunkToken() string {
	if o == nil || IsNil(o.SplunkToken) {
		var ret string
		return ret
	}
	return *o.SplunkToken
}

// GetSplunkTokenOk returns a tuple with the SplunkToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SplunkLogForwardingConfig) GetSplunkTokenOk() (*string, bool) {
	if o == nil || IsNil(o.SplunkToken) {
		return nil, false
	}
	return o.SplunkToken, true
}

// HasSplunkToken returns a boolean if a field has been set.
func (o *SplunkLogForwardingConfig) HasSplunkToken() bool {
	if o != nil && !IsNil(o.SplunkToken) {
		return true
	}

	return false
}

// SetSplunkToken gets a reference to the given string and assigns it to the SplunkToken field.
func (o *SplunkLogForwardingConfig) SetSplunkToken(v string) {
	o.SplunkToken = &v
}

// GetSplunkUrl returns the SplunkUrl field value if set, zero value otherwise.
func (o *SplunkLogForwardingConfig) GetSplunkUrl() string {
	if o == nil || IsNil(o.SplunkUrl) {
		var ret string
		return ret
	}
	return *o.SplunkUrl
}

// GetSplunkUrlOk returns a tuple with the SplunkUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SplunkLogForwardingConfig) GetSplunkUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SplunkUrl) {
		return nil, false
	}
	return o.SplunkUrl, true
}

// HasSplunkUrl returns a boolean if a field has been set.
func (o *SplunkLogForwardingConfig) HasSplunkUrl() bool {
	if o != nil && !IsNil(o.SplunkUrl) {
		return true
	}

	return false
}

// SetSplunkUrl gets a reference to the given string and assigns it to the SplunkUrl field.
func (o *SplunkLogForwardingConfig) SetSplunkUrl(v string) {
	o.SplunkUrl = &v
}

func (o SplunkLogForwardingConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SplunkLogForwardingConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SplunkIndex) {
		toSerialize["splunk_index"] = o.SplunkIndex
	}
	if !IsNil(o.SplunkSource) {
		toSerialize["splunk_source"] = o.SplunkSource
	}
	if !IsNil(o.SplunkSourcetype) {
		toSerialize["splunk_sourcetype"] = o.SplunkSourcetype
	}
	if !IsNil(o.SplunkToken) {
		toSerialize["splunk_token"] = o.SplunkToken
	}
	if !IsNil(o.SplunkUrl) {
		toSerialize["splunk_url"] = o.SplunkUrl
	}
	return toSerialize, nil
}

type NullableSplunkLogForwardingConfig struct {
	value *SplunkLogForwardingConfig
	isSet bool
}

func (v NullableSplunkLogForwardingConfig) Get() *SplunkLogForwardingConfig {
	return v.value
}

func (v *NullableSplunkLogForwardingConfig) Set(val *SplunkLogForwardingConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableSplunkLogForwardingConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableSplunkLogForwardingConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSplunkLogForwardingConfig(val *SplunkLogForwardingConfig) *NullableSplunkLogForwardingConfig {
	return &NullableSplunkLogForwardingConfig{value: val, isSet: true}
}

func (v NullableSplunkLogForwardingConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSplunkLogForwardingConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


