/*
Akeyless API

The purpose of this application is to provide access to Akeyless API.

API version: 3.0
Contact: support@akeyless.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package akeyless

import (
	"encoding/json"
)

// checks if the PoliciesListOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PoliciesListOutput{}

// PoliciesListOutput struct for PoliciesListOutput
type PoliciesListOutput struct {
	Policies []PolicyOutput `json:"policies,omitempty"`
}

// NewPoliciesListOutput instantiates a new PoliciesListOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPoliciesListOutput() *PoliciesListOutput {
	this := PoliciesListOutput{}
	return &this
}

// NewPoliciesListOutputWithDefaults instantiates a new PoliciesListOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPoliciesListOutputWithDefaults() *PoliciesListOutput {
	this := PoliciesListOutput{}
	return &this
}

// GetPolicies returns the Policies field value if set, zero value otherwise.
func (o *PoliciesListOutput) GetPolicies() []PolicyOutput {
	if o == nil || IsNil(o.Policies) {
		var ret []PolicyOutput
		return ret
	}
	return o.Policies
}

// GetPoliciesOk returns a tuple with the Policies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PoliciesListOutput) GetPoliciesOk() ([]PolicyOutput, bool) {
	if o == nil || IsNil(o.Policies) {
		return nil, false
	}
	return o.Policies, true
}

// HasPolicies returns a boolean if a field has been set.
func (o *PoliciesListOutput) HasPolicies() bool {
	if o != nil && !IsNil(o.Policies) {
		return true
	}

	return false
}

// SetPolicies gets a reference to the given []PolicyOutput and assigns it to the Policies field.
func (o *PoliciesListOutput) SetPolicies(v []PolicyOutput) {
	o.Policies = v
}

func (o PoliciesListOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PoliciesListOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Policies) {
		toSerialize["policies"] = o.Policies
	}
	return toSerialize, nil
}

type NullablePoliciesListOutput struct {
	value *PoliciesListOutput
	isSet bool
}

func (v NullablePoliciesListOutput) Get() *PoliciesListOutput {
	return v.value
}

func (v *NullablePoliciesListOutput) Set(val *PoliciesListOutput) {
	v.value = val
	v.isSet = true
}

func (v NullablePoliciesListOutput) IsSet() bool {
	return v.isSet
}

func (v *NullablePoliciesListOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePoliciesListOutput(val *PoliciesListOutput) *NullablePoliciesListOutput {
	return &NullablePoliciesListOutput{value: val, isSet: true}
}

func (v NullablePoliciesListOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePoliciesListOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


