/*
Akeyless API

The purpose of this application is to provide access to Akeyless API.

API version: 2.0
Contact: support@akeyless.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package akeyless

import (
	"encoding/json"
)

// checks if the GatewayRevokeTmpUsers type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GatewayRevokeTmpUsers{}

// GatewayRevokeTmpUsers gatewayRevokeTmpUsers is a command that revoke producer tmp user
type GatewayRevokeTmpUsers struct {
	// Deprecated: has no effect
	Host *string `json:"host,omitempty"`
	// Set output format to JSON
	Json *bool `json:"json,omitempty"`
	// Producer Name
	Name string `json:"name"`
	// Revoke All Temp Creds
	RevokeAll *bool `json:"revoke-all,omitempty"`
	// Soft Delete
	SoftDelete *bool `json:"soft-delete,omitempty"`
	// Tmp Creds ID
	TmpCredsId string `json:"tmp-creds-id"`
	// Authentication token (see `/auth` and `/configure`)
	Token *string `json:"token,omitempty"`
	// The universal identity token, Required only for universal_identity authentication
	UidToken *string `json:"uid-token,omitempty"`
}

// NewGatewayRevokeTmpUsers instantiates a new GatewayRevokeTmpUsers object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGatewayRevokeTmpUsers(name string, tmpCredsId string) *GatewayRevokeTmpUsers {
	this := GatewayRevokeTmpUsers{}
	var json bool = false
	this.Json = &json
	this.Name = name
	this.TmpCredsId = tmpCredsId
	return &this
}

// NewGatewayRevokeTmpUsersWithDefaults instantiates a new GatewayRevokeTmpUsers object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGatewayRevokeTmpUsersWithDefaults() *GatewayRevokeTmpUsers {
	this := GatewayRevokeTmpUsers{}
	var json bool = false
	this.Json = &json
	var tmpCredsId string = "demo_default_tmp_creds_id_for_sdk_bc"
	this.TmpCredsId = tmpCredsId
	return &this
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *GatewayRevokeTmpUsers) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayRevokeTmpUsers) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *GatewayRevokeTmpUsers) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *GatewayRevokeTmpUsers) SetHost(v string) {
	o.Host = &v
}

// GetJson returns the Json field value if set, zero value otherwise.
func (o *GatewayRevokeTmpUsers) GetJson() bool {
	if o == nil || IsNil(o.Json) {
		var ret bool
		return ret
	}
	return *o.Json
}

// GetJsonOk returns a tuple with the Json field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayRevokeTmpUsers) GetJsonOk() (*bool, bool) {
	if o == nil || IsNil(o.Json) {
		return nil, false
	}
	return o.Json, true
}

// HasJson returns a boolean if a field has been set.
func (o *GatewayRevokeTmpUsers) HasJson() bool {
	if o != nil && !IsNil(o.Json) {
		return true
	}

	return false
}

// SetJson gets a reference to the given bool and assigns it to the Json field.
func (o *GatewayRevokeTmpUsers) SetJson(v bool) {
	o.Json = &v
}

// GetName returns the Name field value
func (o *GatewayRevokeTmpUsers) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GatewayRevokeTmpUsers) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GatewayRevokeTmpUsers) SetName(v string) {
	o.Name = v
}

// GetRevokeAll returns the RevokeAll field value if set, zero value otherwise.
func (o *GatewayRevokeTmpUsers) GetRevokeAll() bool {
	if o == nil || IsNil(o.RevokeAll) {
		var ret bool
		return ret
	}
	return *o.RevokeAll
}

// GetRevokeAllOk returns a tuple with the RevokeAll field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayRevokeTmpUsers) GetRevokeAllOk() (*bool, bool) {
	if o == nil || IsNil(o.RevokeAll) {
		return nil, false
	}
	return o.RevokeAll, true
}

// HasRevokeAll returns a boolean if a field has been set.
func (o *GatewayRevokeTmpUsers) HasRevokeAll() bool {
	if o != nil && !IsNil(o.RevokeAll) {
		return true
	}

	return false
}

// SetRevokeAll gets a reference to the given bool and assigns it to the RevokeAll field.
func (o *GatewayRevokeTmpUsers) SetRevokeAll(v bool) {
	o.RevokeAll = &v
}

// GetSoftDelete returns the SoftDelete field value if set, zero value otherwise.
func (o *GatewayRevokeTmpUsers) GetSoftDelete() bool {
	if o == nil || IsNil(o.SoftDelete) {
		var ret bool
		return ret
	}
	return *o.SoftDelete
}

// GetSoftDeleteOk returns a tuple with the SoftDelete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayRevokeTmpUsers) GetSoftDeleteOk() (*bool, bool) {
	if o == nil || IsNil(o.SoftDelete) {
		return nil, false
	}
	return o.SoftDelete, true
}

// HasSoftDelete returns a boolean if a field has been set.
func (o *GatewayRevokeTmpUsers) HasSoftDelete() bool {
	if o != nil && !IsNil(o.SoftDelete) {
		return true
	}

	return false
}

// SetSoftDelete gets a reference to the given bool and assigns it to the SoftDelete field.
func (o *GatewayRevokeTmpUsers) SetSoftDelete(v bool) {
	o.SoftDelete = &v
}

// GetTmpCredsId returns the TmpCredsId field value
func (o *GatewayRevokeTmpUsers) GetTmpCredsId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TmpCredsId
}

// GetTmpCredsIdOk returns a tuple with the TmpCredsId field value
// and a boolean to check if the value has been set.
func (o *GatewayRevokeTmpUsers) GetTmpCredsIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TmpCredsId, true
}

// SetTmpCredsId sets field value
func (o *GatewayRevokeTmpUsers) SetTmpCredsId(v string) {
	o.TmpCredsId = v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *GatewayRevokeTmpUsers) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayRevokeTmpUsers) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *GatewayRevokeTmpUsers) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *GatewayRevokeTmpUsers) SetToken(v string) {
	o.Token = &v
}

// GetUidToken returns the UidToken field value if set, zero value otherwise.
func (o *GatewayRevokeTmpUsers) GetUidToken() string {
	if o == nil || IsNil(o.UidToken) {
		var ret string
		return ret
	}
	return *o.UidToken
}

// GetUidTokenOk returns a tuple with the UidToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GatewayRevokeTmpUsers) GetUidTokenOk() (*string, bool) {
	if o == nil || IsNil(o.UidToken) {
		return nil, false
	}
	return o.UidToken, true
}

// HasUidToken returns a boolean if a field has been set.
func (o *GatewayRevokeTmpUsers) HasUidToken() bool {
	if o != nil && !IsNil(o.UidToken) {
		return true
	}

	return false
}

// SetUidToken gets a reference to the given string and assigns it to the UidToken field.
func (o *GatewayRevokeTmpUsers) SetUidToken(v string) {
	o.UidToken = &v
}

func (o GatewayRevokeTmpUsers) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GatewayRevokeTmpUsers) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.Json) {
		toSerialize["json"] = o.Json
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.RevokeAll) {
		toSerialize["revoke-all"] = o.RevokeAll
	}
	if !IsNil(o.SoftDelete) {
		toSerialize["soft-delete"] = o.SoftDelete
	}
	toSerialize["tmp-creds-id"] = o.TmpCredsId
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.UidToken) {
		toSerialize["uid-token"] = o.UidToken
	}
	return toSerialize, nil
}

type NullableGatewayRevokeTmpUsers struct {
	value *GatewayRevokeTmpUsers
	isSet bool
}

func (v NullableGatewayRevokeTmpUsers) Get() *GatewayRevokeTmpUsers {
	return v.value
}

func (v *NullableGatewayRevokeTmpUsers) Set(val *GatewayRevokeTmpUsers) {
	v.value = val
	v.isSet = true
}

func (v NullableGatewayRevokeTmpUsers) IsSet() bool {
	return v.isSet
}

func (v *NullableGatewayRevokeTmpUsers) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGatewayRevokeTmpUsers(val *GatewayRevokeTmpUsers) *NullableGatewayRevokeTmpUsers {
	return &NullableGatewayRevokeTmpUsers{value: val, isSet: true}
}

func (v NullableGatewayRevokeTmpUsers) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGatewayRevokeTmpUsers) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


