/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * API version: 2.0.0
 * Contact: support@akeyless.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package akeyless

import (
	"encoding/json"
)

// DecryptFileOutput struct for DecryptFileOutput
type DecryptFileOutput struct {
	Path *string `json:"path,omitempty"`
	PlainText *string `json:"plain_text,omitempty"`
}

// NewDecryptFileOutput instantiates a new DecryptFileOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDecryptFileOutput() *DecryptFileOutput {
	this := DecryptFileOutput{}
	return &this
}

// NewDecryptFileOutputWithDefaults instantiates a new DecryptFileOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDecryptFileOutputWithDefaults() *DecryptFileOutput {
	this := DecryptFileOutput{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *DecryptFileOutput) GetPath() string {
	if o == nil || o.Path == nil {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecryptFileOutput) GetPathOk() (*string, bool) {
	if o == nil || o.Path == nil {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *DecryptFileOutput) HasPath() bool {
	if o != nil && o.Path != nil {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *DecryptFileOutput) SetPath(v string) {
	o.Path = &v
}

// GetPlainText returns the PlainText field value if set, zero value otherwise.
func (o *DecryptFileOutput) GetPlainText() string {
	if o == nil || o.PlainText == nil {
		var ret string
		return ret
	}
	return *o.PlainText
}

// GetPlainTextOk returns a tuple with the PlainText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DecryptFileOutput) GetPlainTextOk() (*string, bool) {
	if o == nil || o.PlainText == nil {
		return nil, false
	}
	return o.PlainText, true
}

// HasPlainText returns a boolean if a field has been set.
func (o *DecryptFileOutput) HasPlainText() bool {
	if o != nil && o.PlainText != nil {
		return true
	}

	return false
}

// SetPlainText gets a reference to the given string and assigns it to the PlainText field.
func (o *DecryptFileOutput) SetPlainText(v string) {
	o.PlainText = &v
}

func (o DecryptFileOutput) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Path != nil {
		toSerialize["path"] = o.Path
	}
	if o.PlainText != nil {
		toSerialize["plain_text"] = o.PlainText
	}
	return json.Marshal(toSerialize)
}

type NullableDecryptFileOutput struct {
	value *DecryptFileOutput
	isSet bool
}

func (v NullableDecryptFileOutput) Get() *DecryptFileOutput {
	return v.value
}

func (v *NullableDecryptFileOutput) Set(val *DecryptFileOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableDecryptFileOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableDecryptFileOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDecryptFileOutput(val *DecryptFileOutput) *NullableDecryptFileOutput {
	return &NullableDecryptFileOutput{value: val, isSet: true}
}

func (v NullableDecryptFileOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDecryptFileOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


