/*
Akeyless API

The purpose of this application is to provide access to Akeyless API.

API version: 3.0
Contact: support@akeyless.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package akeyless

import (
	"encoding/json"
)

// checks if the CertificateDiscoveryOutput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateDiscoveryOutput{}

// CertificateDiscoveryOutput struct for CertificateDiscoveryOutput
type CertificateDiscoveryOutput struct {
	Results *ScanResults `json:"results,omitempty"`
}

// NewCertificateDiscoveryOutput instantiates a new CertificateDiscoveryOutput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateDiscoveryOutput() *CertificateDiscoveryOutput {
	this := CertificateDiscoveryOutput{}
	return &this
}

// NewCertificateDiscoveryOutputWithDefaults instantiates a new CertificateDiscoveryOutput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateDiscoveryOutputWithDefaults() *CertificateDiscoveryOutput {
	this := CertificateDiscoveryOutput{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *CertificateDiscoveryOutput) GetResults() ScanResults {
	if o == nil || IsNil(o.Results) {
		var ret ScanResults
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateDiscoveryOutput) GetResultsOk() (*ScanResults, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *CertificateDiscoveryOutput) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given ScanResults and assigns it to the Results field.
func (o *CertificateDiscoveryOutput) SetResults(v ScanResults) {
	o.Results = &v
}

func (o CertificateDiscoveryOutput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateDiscoveryOutput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	return toSerialize, nil
}

type NullableCertificateDiscoveryOutput struct {
	value *CertificateDiscoveryOutput
	isSet bool
}

func (v NullableCertificateDiscoveryOutput) Get() *CertificateDiscoveryOutput {
	return v.value
}

func (v *NullableCertificateDiscoveryOutput) Set(val *CertificateDiscoveryOutput) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateDiscoveryOutput) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateDiscoveryOutput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateDiscoveryOutput(val *CertificateDiscoveryOutput) *NullableCertificateDiscoveryOutput {
	return &NullableCertificateDiscoveryOutput{value: val, isSet: true}
}

func (v NullableCertificateDiscoveryOutput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateDiscoveryOutput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


