/*
 * Akeyless API
 *
 * The purpose of this application is to provide access to Akeyless API.
 *
 * API version: 2.0
 * Contact: support@akeyless.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package akeyless

import (
	"encoding/json"
)

// LinkedTargetDetails LinkedTargetDetails
type LinkedTargetDetails struct {
	// key hostname, value description
	Hosts *map[string]string `json:"hosts,omitempty"`
}

// NewLinkedTargetDetails instantiates a new LinkedTargetDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkedTargetDetails() *LinkedTargetDetails {
	this := LinkedTargetDetails{}
	return &this
}

// NewLinkedTargetDetailsWithDefaults instantiates a new LinkedTargetDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkedTargetDetailsWithDefaults() *LinkedTargetDetails {
	this := LinkedTargetDetails{}
	return &this
}

// GetHosts returns the Hosts field value if set, zero value otherwise.
func (o *LinkedTargetDetails) GetHosts() map[string]string {
	if o == nil || o.Hosts == nil {
		var ret map[string]string
		return ret
	}
	return *o.Hosts
}

// GetHostsOk returns a tuple with the Hosts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LinkedTargetDetails) GetHostsOk() (*map[string]string, bool) {
	if o == nil || o.Hosts == nil {
		return nil, false
	}
	return o.Hosts, true
}

// HasHosts returns a boolean if a field has been set.
func (o *LinkedTargetDetails) HasHosts() bool {
	if o != nil && o.Hosts != nil {
		return true
	}

	return false
}

// SetHosts gets a reference to the given map[string]string and assigns it to the Hosts field.
func (o *LinkedTargetDetails) SetHosts(v map[string]string) {
	o.Hosts = &v
}

func (o LinkedTargetDetails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Hosts != nil {
		toSerialize["hosts"] = o.Hosts
	}
	return json.Marshal(toSerialize)
}

type NullableLinkedTargetDetails struct {
	value *LinkedTargetDetails
	isSet bool
}

func (v NullableLinkedTargetDetails) Get() *LinkedTargetDetails {
	return v.value
}

func (v *NullableLinkedTargetDetails) Set(val *LinkedTargetDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkedTargetDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkedTargetDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkedTargetDetails(val *LinkedTargetDetails) *NullableLinkedTargetDetails {
	return &NullableLinkedTargetDetails{value: val, isSet: true}
}

func (v NullableLinkedTargetDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkedTargetDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


