/*
Akeyless API

The purpose of this application is to provide access to Akeyless API.

API version: 3.0
Contact: support@akeyless.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package akeyless

import (
	"encoding/json"
)

// checks if the FileInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileInfo{}

// FileInfo struct for FileInfo
type FileInfo struct {
	BlobStorageKey *string `json:"blob_storage_key,omitempty"`
	ClientFileSha256 *string `json:"client_file_sha256,omitempty"`
	ContentType *string `json:"content_type,omitempty"`
	DerivationData *string `json:"derivation_data,omitempty"`
	EncryptedBlobSha256 *string `json:"encrypted_blob_sha256,omitempty"`
	EncryptedSizeBytes *int64 `json:"encrypted_size_bytes,omitempty"`
	EtagAtComplete *string `json:"etag_at_complete,omitempty"`
	Extension *string `json:"extension,omitempty"`
	FileId *string `json:"file_id,omitempty"`
	Filename *string `json:"filename,omitempty"`
	PlainSizeBytes *int64 `json:"plain_size_bytes,omitempty"`
	PreviousActiveFileInfo *FileInfo `json:"previous_active_file_info,omitempty"`
	PreviousBlobStorageKey *string `json:"previous_blob_storage_key,omitempty"`
	ProtectionKeyName *string `json:"protection_key_name,omitempty"`
	ProtectionKeyVersion *int32 `json:"protection_key_version,omitempty"`
	Status *string `json:"status,omitempty"`
	TransactionOwner *string `json:"transaction_owner,omitempty"`
}

// NewFileInfo instantiates a new FileInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileInfo() *FileInfo {
	this := FileInfo{}
	return &this
}

// NewFileInfoWithDefaults instantiates a new FileInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileInfoWithDefaults() *FileInfo {
	this := FileInfo{}
	return &this
}

// GetBlobStorageKey returns the BlobStorageKey field value if set, zero value otherwise.
func (o *FileInfo) GetBlobStorageKey() string {
	if o == nil || IsNil(o.BlobStorageKey) {
		var ret string
		return ret
	}
	return *o.BlobStorageKey
}

// GetBlobStorageKeyOk returns a tuple with the BlobStorageKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetBlobStorageKeyOk() (*string, bool) {
	if o == nil || IsNil(o.BlobStorageKey) {
		return nil, false
	}
	return o.BlobStorageKey, true
}

// HasBlobStorageKey returns a boolean if a field has been set.
func (o *FileInfo) HasBlobStorageKey() bool {
	if o != nil && !IsNil(o.BlobStorageKey) {
		return true
	}

	return false
}

// SetBlobStorageKey gets a reference to the given string and assigns it to the BlobStorageKey field.
func (o *FileInfo) SetBlobStorageKey(v string) {
	o.BlobStorageKey = &v
}

// GetClientFileSha256 returns the ClientFileSha256 field value if set, zero value otherwise.
func (o *FileInfo) GetClientFileSha256() string {
	if o == nil || IsNil(o.ClientFileSha256) {
		var ret string
		return ret
	}
	return *o.ClientFileSha256
}

// GetClientFileSha256Ok returns a tuple with the ClientFileSha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetClientFileSha256Ok() (*string, bool) {
	if o == nil || IsNil(o.ClientFileSha256) {
		return nil, false
	}
	return o.ClientFileSha256, true
}

// HasClientFileSha256 returns a boolean if a field has been set.
func (o *FileInfo) HasClientFileSha256() bool {
	if o != nil && !IsNil(o.ClientFileSha256) {
		return true
	}

	return false
}

// SetClientFileSha256 gets a reference to the given string and assigns it to the ClientFileSha256 field.
func (o *FileInfo) SetClientFileSha256(v string) {
	o.ClientFileSha256 = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *FileInfo) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *FileInfo) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *FileInfo) SetContentType(v string) {
	o.ContentType = &v
}

// GetDerivationData returns the DerivationData field value if set, zero value otherwise.
func (o *FileInfo) GetDerivationData() string {
	if o == nil || IsNil(o.DerivationData) {
		var ret string
		return ret
	}
	return *o.DerivationData
}

// GetDerivationDataOk returns a tuple with the DerivationData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetDerivationDataOk() (*string, bool) {
	if o == nil || IsNil(o.DerivationData) {
		return nil, false
	}
	return o.DerivationData, true
}

// HasDerivationData returns a boolean if a field has been set.
func (o *FileInfo) HasDerivationData() bool {
	if o != nil && !IsNil(o.DerivationData) {
		return true
	}

	return false
}

// SetDerivationData gets a reference to the given string and assigns it to the DerivationData field.
func (o *FileInfo) SetDerivationData(v string) {
	o.DerivationData = &v
}

// GetEncryptedBlobSha256 returns the EncryptedBlobSha256 field value if set, zero value otherwise.
func (o *FileInfo) GetEncryptedBlobSha256() string {
	if o == nil || IsNil(o.EncryptedBlobSha256) {
		var ret string
		return ret
	}
	return *o.EncryptedBlobSha256
}

// GetEncryptedBlobSha256Ok returns a tuple with the EncryptedBlobSha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetEncryptedBlobSha256Ok() (*string, bool) {
	if o == nil || IsNil(o.EncryptedBlobSha256) {
		return nil, false
	}
	return o.EncryptedBlobSha256, true
}

// HasEncryptedBlobSha256 returns a boolean if a field has been set.
func (o *FileInfo) HasEncryptedBlobSha256() bool {
	if o != nil && !IsNil(o.EncryptedBlobSha256) {
		return true
	}

	return false
}

// SetEncryptedBlobSha256 gets a reference to the given string and assigns it to the EncryptedBlobSha256 field.
func (o *FileInfo) SetEncryptedBlobSha256(v string) {
	o.EncryptedBlobSha256 = &v
}

// GetEncryptedSizeBytes returns the EncryptedSizeBytes field value if set, zero value otherwise.
func (o *FileInfo) GetEncryptedSizeBytes() int64 {
	if o == nil || IsNil(o.EncryptedSizeBytes) {
		var ret int64
		return ret
	}
	return *o.EncryptedSizeBytes
}

// GetEncryptedSizeBytesOk returns a tuple with the EncryptedSizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetEncryptedSizeBytesOk() (*int64, bool) {
	if o == nil || IsNil(o.EncryptedSizeBytes) {
		return nil, false
	}
	return o.EncryptedSizeBytes, true
}

// HasEncryptedSizeBytes returns a boolean if a field has been set.
func (o *FileInfo) HasEncryptedSizeBytes() bool {
	if o != nil && !IsNil(o.EncryptedSizeBytes) {
		return true
	}

	return false
}

// SetEncryptedSizeBytes gets a reference to the given int64 and assigns it to the EncryptedSizeBytes field.
func (o *FileInfo) SetEncryptedSizeBytes(v int64) {
	o.EncryptedSizeBytes = &v
}

// GetEtagAtComplete returns the EtagAtComplete field value if set, zero value otherwise.
func (o *FileInfo) GetEtagAtComplete() string {
	if o == nil || IsNil(o.EtagAtComplete) {
		var ret string
		return ret
	}
	return *o.EtagAtComplete
}

// GetEtagAtCompleteOk returns a tuple with the EtagAtComplete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetEtagAtCompleteOk() (*string, bool) {
	if o == nil || IsNil(o.EtagAtComplete) {
		return nil, false
	}
	return o.EtagAtComplete, true
}

// HasEtagAtComplete returns a boolean if a field has been set.
func (o *FileInfo) HasEtagAtComplete() bool {
	if o != nil && !IsNil(o.EtagAtComplete) {
		return true
	}

	return false
}

// SetEtagAtComplete gets a reference to the given string and assigns it to the EtagAtComplete field.
func (o *FileInfo) SetEtagAtComplete(v string) {
	o.EtagAtComplete = &v
}

// GetExtension returns the Extension field value if set, zero value otherwise.
func (o *FileInfo) GetExtension() string {
	if o == nil || IsNil(o.Extension) {
		var ret string
		return ret
	}
	return *o.Extension
}

// GetExtensionOk returns a tuple with the Extension field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetExtensionOk() (*string, bool) {
	if o == nil || IsNil(o.Extension) {
		return nil, false
	}
	return o.Extension, true
}

// HasExtension returns a boolean if a field has been set.
func (o *FileInfo) HasExtension() bool {
	if o != nil && !IsNil(o.Extension) {
		return true
	}

	return false
}

// SetExtension gets a reference to the given string and assigns it to the Extension field.
func (o *FileInfo) SetExtension(v string) {
	o.Extension = &v
}

// GetFileId returns the FileId field value if set, zero value otherwise.
func (o *FileInfo) GetFileId() string {
	if o == nil || IsNil(o.FileId) {
		var ret string
		return ret
	}
	return *o.FileId
}

// GetFileIdOk returns a tuple with the FileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetFileIdOk() (*string, bool) {
	if o == nil || IsNil(o.FileId) {
		return nil, false
	}
	return o.FileId, true
}

// HasFileId returns a boolean if a field has been set.
func (o *FileInfo) HasFileId() bool {
	if o != nil && !IsNil(o.FileId) {
		return true
	}

	return false
}

// SetFileId gets a reference to the given string and assigns it to the FileId field.
func (o *FileInfo) SetFileId(v string) {
	o.FileId = &v
}

// GetFilename returns the Filename field value if set, zero value otherwise.
func (o *FileInfo) GetFilename() string {
	if o == nil || IsNil(o.Filename) {
		var ret string
		return ret
	}
	return *o.Filename
}

// GetFilenameOk returns a tuple with the Filename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetFilenameOk() (*string, bool) {
	if o == nil || IsNil(o.Filename) {
		return nil, false
	}
	return o.Filename, true
}

// HasFilename returns a boolean if a field has been set.
func (o *FileInfo) HasFilename() bool {
	if o != nil && !IsNil(o.Filename) {
		return true
	}

	return false
}

// SetFilename gets a reference to the given string and assigns it to the Filename field.
func (o *FileInfo) SetFilename(v string) {
	o.Filename = &v
}

// GetPlainSizeBytes returns the PlainSizeBytes field value if set, zero value otherwise.
func (o *FileInfo) GetPlainSizeBytes() int64 {
	if o == nil || IsNil(o.PlainSizeBytes) {
		var ret int64
		return ret
	}
	return *o.PlainSizeBytes
}

// GetPlainSizeBytesOk returns a tuple with the PlainSizeBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetPlainSizeBytesOk() (*int64, bool) {
	if o == nil || IsNil(o.PlainSizeBytes) {
		return nil, false
	}
	return o.PlainSizeBytes, true
}

// HasPlainSizeBytes returns a boolean if a field has been set.
func (o *FileInfo) HasPlainSizeBytes() bool {
	if o != nil && !IsNil(o.PlainSizeBytes) {
		return true
	}

	return false
}

// SetPlainSizeBytes gets a reference to the given int64 and assigns it to the PlainSizeBytes field.
func (o *FileInfo) SetPlainSizeBytes(v int64) {
	o.PlainSizeBytes = &v
}

// GetPreviousActiveFileInfo returns the PreviousActiveFileInfo field value if set, zero value otherwise.
func (o *FileInfo) GetPreviousActiveFileInfo() FileInfo {
	if o == nil || IsNil(o.PreviousActiveFileInfo) {
		var ret FileInfo
		return ret
	}
	return *o.PreviousActiveFileInfo
}

// GetPreviousActiveFileInfoOk returns a tuple with the PreviousActiveFileInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetPreviousActiveFileInfoOk() (*FileInfo, bool) {
	if o == nil || IsNil(o.PreviousActiveFileInfo) {
		return nil, false
	}
	return o.PreviousActiveFileInfo, true
}

// HasPreviousActiveFileInfo returns a boolean if a field has been set.
func (o *FileInfo) HasPreviousActiveFileInfo() bool {
	if o != nil && !IsNil(o.PreviousActiveFileInfo) {
		return true
	}

	return false
}

// SetPreviousActiveFileInfo gets a reference to the given FileInfo and assigns it to the PreviousActiveFileInfo field.
func (o *FileInfo) SetPreviousActiveFileInfo(v FileInfo) {
	o.PreviousActiveFileInfo = &v
}

// GetPreviousBlobStorageKey returns the PreviousBlobStorageKey field value if set, zero value otherwise.
func (o *FileInfo) GetPreviousBlobStorageKey() string {
	if o == nil || IsNil(o.PreviousBlobStorageKey) {
		var ret string
		return ret
	}
	return *o.PreviousBlobStorageKey
}

// GetPreviousBlobStorageKeyOk returns a tuple with the PreviousBlobStorageKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetPreviousBlobStorageKeyOk() (*string, bool) {
	if o == nil || IsNil(o.PreviousBlobStorageKey) {
		return nil, false
	}
	return o.PreviousBlobStorageKey, true
}

// HasPreviousBlobStorageKey returns a boolean if a field has been set.
func (o *FileInfo) HasPreviousBlobStorageKey() bool {
	if o != nil && !IsNil(o.PreviousBlobStorageKey) {
		return true
	}

	return false
}

// SetPreviousBlobStorageKey gets a reference to the given string and assigns it to the PreviousBlobStorageKey field.
func (o *FileInfo) SetPreviousBlobStorageKey(v string) {
	o.PreviousBlobStorageKey = &v
}

// GetProtectionKeyName returns the ProtectionKeyName field value if set, zero value otherwise.
func (o *FileInfo) GetProtectionKeyName() string {
	if o == nil || IsNil(o.ProtectionKeyName) {
		var ret string
		return ret
	}
	return *o.ProtectionKeyName
}

// GetProtectionKeyNameOk returns a tuple with the ProtectionKeyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetProtectionKeyNameOk() (*string, bool) {
	if o == nil || IsNil(o.ProtectionKeyName) {
		return nil, false
	}
	return o.ProtectionKeyName, true
}

// HasProtectionKeyName returns a boolean if a field has been set.
func (o *FileInfo) HasProtectionKeyName() bool {
	if o != nil && !IsNil(o.ProtectionKeyName) {
		return true
	}

	return false
}

// SetProtectionKeyName gets a reference to the given string and assigns it to the ProtectionKeyName field.
func (o *FileInfo) SetProtectionKeyName(v string) {
	o.ProtectionKeyName = &v
}

// GetProtectionKeyVersion returns the ProtectionKeyVersion field value if set, zero value otherwise.
func (o *FileInfo) GetProtectionKeyVersion() int32 {
	if o == nil || IsNil(o.ProtectionKeyVersion) {
		var ret int32
		return ret
	}
	return *o.ProtectionKeyVersion
}

// GetProtectionKeyVersionOk returns a tuple with the ProtectionKeyVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetProtectionKeyVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.ProtectionKeyVersion) {
		return nil, false
	}
	return o.ProtectionKeyVersion, true
}

// HasProtectionKeyVersion returns a boolean if a field has been set.
func (o *FileInfo) HasProtectionKeyVersion() bool {
	if o != nil && !IsNil(o.ProtectionKeyVersion) {
		return true
	}

	return false
}

// SetProtectionKeyVersion gets a reference to the given int32 and assigns it to the ProtectionKeyVersion field.
func (o *FileInfo) SetProtectionKeyVersion(v int32) {
	o.ProtectionKeyVersion = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *FileInfo) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *FileInfo) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *FileInfo) SetStatus(v string) {
	o.Status = &v
}

// GetTransactionOwner returns the TransactionOwner field value if set, zero value otherwise.
func (o *FileInfo) GetTransactionOwner() string {
	if o == nil || IsNil(o.TransactionOwner) {
		var ret string
		return ret
	}
	return *o.TransactionOwner
}

// GetTransactionOwnerOk returns a tuple with the TransactionOwner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileInfo) GetTransactionOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.TransactionOwner) {
		return nil, false
	}
	return o.TransactionOwner, true
}

// HasTransactionOwner returns a boolean if a field has been set.
func (o *FileInfo) HasTransactionOwner() bool {
	if o != nil && !IsNil(o.TransactionOwner) {
		return true
	}

	return false
}

// SetTransactionOwner gets a reference to the given string and assigns it to the TransactionOwner field.
func (o *FileInfo) SetTransactionOwner(v string) {
	o.TransactionOwner = &v
}

func (o FileInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BlobStorageKey) {
		toSerialize["blob_storage_key"] = o.BlobStorageKey
	}
	if !IsNil(o.ClientFileSha256) {
		toSerialize["client_file_sha256"] = o.ClientFileSha256
	}
	if !IsNil(o.ContentType) {
		toSerialize["content_type"] = o.ContentType
	}
	if !IsNil(o.DerivationData) {
		toSerialize["derivation_data"] = o.DerivationData
	}
	if !IsNil(o.EncryptedBlobSha256) {
		toSerialize["encrypted_blob_sha256"] = o.EncryptedBlobSha256
	}
	if !IsNil(o.EncryptedSizeBytes) {
		toSerialize["encrypted_size_bytes"] = o.EncryptedSizeBytes
	}
	if !IsNil(o.EtagAtComplete) {
		toSerialize["etag_at_complete"] = o.EtagAtComplete
	}
	if !IsNil(o.Extension) {
		toSerialize["extension"] = o.Extension
	}
	if !IsNil(o.FileId) {
		toSerialize["file_id"] = o.FileId
	}
	if !IsNil(o.Filename) {
		toSerialize["filename"] = o.Filename
	}
	if !IsNil(o.PlainSizeBytes) {
		toSerialize["plain_size_bytes"] = o.PlainSizeBytes
	}
	if !IsNil(o.PreviousActiveFileInfo) {
		toSerialize["previous_active_file_info"] = o.PreviousActiveFileInfo
	}
	if !IsNil(o.PreviousBlobStorageKey) {
		toSerialize["previous_blob_storage_key"] = o.PreviousBlobStorageKey
	}
	if !IsNil(o.ProtectionKeyName) {
		toSerialize["protection_key_name"] = o.ProtectionKeyName
	}
	if !IsNil(o.ProtectionKeyVersion) {
		toSerialize["protection_key_version"] = o.ProtectionKeyVersion
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.TransactionOwner) {
		toSerialize["transaction_owner"] = o.TransactionOwner
	}
	return toSerialize, nil
}

type NullableFileInfo struct {
	value *FileInfo
	isSet bool
}

func (v NullableFileInfo) Get() *FileInfo {
	return v.value
}

func (v *NullableFileInfo) Set(val *FileInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableFileInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableFileInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileInfo(val *FileInfo) *NullableFileInfo {
	return &NullableFileInfo{value: val, isSet: true}
}

func (v NullableFileInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


