/*
Akeyless API

The purpose of this application is to provide access to Akeyless API.

API version: 3.0
Contact: support@akeyless.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package akeyless

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RotatedSecretCreateHanadb type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RotatedSecretCreateHanadb{}

// RotatedSecretCreateHanadb struct for RotatedSecretCreateHanadb
type RotatedSecretCreateHanadb struct {
	// Enable or disable Agentic Runtime Authority rule enforcement for this item. When false, user-defined input/output rules are stored but not enforced; the base security validation still runs.  AraEnabled is tri-state (nil/true/false), not a plain bool: it self-encodes its wire value (see akl.OptionalBool) so an explicit false survives the curl-proxy relay instead of being dropped like a default-false bool flag.
	AraEnabled *bool `json:"ara-enabled,omitempty"`
	// The credentials to connect with use-user-creds/use-target-creds
	AuthenticationCredentials *string `json:"authentication-credentials,omitempty"`
	AutoRotate *string `json:"auto-rotate,omitempty"`
	// Protection from accidental deletion of this object [true/false]
	DeleteProtection *string `json:"delete_protection,omitempty"`
	// Description of the object
	Description *string `json:"description,omitempty"`
	// EnableAra is the documented spelling of AraEnabled. Both set the same field; --ara-enabled shipped first and stays as an undocumented alias so existing scripts and the Terraform provider keep working.
	EnableAgenticRuntimeAuthority *bool `json:"enable-agentic-runtime-authority,omitempty"`
	// Turns on AI Quorum checks for this item.
	EnableAiQuorum *bool `json:"enable-ai-quorum,omitempty"`
	// Agentic input rule in name=...,rule=... format (e.g. name=rule1,rule=Sanitize input)
	InputRule []string `json:"input-rule,omitempty"`
	// Additional custom fields to associate with the item
	ItemCustomFields *map[string]string `json:"item-custom-fields,omitempty"`
	// Set output format to JSON
	Json *bool `json:"json,omitempty"`
	Key *string `json:"key,omitempty"`
	// Lock this secret after each successful value read
	LockOnRead *string `json:"lock-on-read,omitempty"`
	// Lock TTL in minutes
	LockTtl *string `json:"lock-ttl,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	MaxVersions *string `json:"max-versions,omitempty"`
	// Rotated secret name
	Name string `json:"name"`
	// Agentic output rule in name=...,rule=... format (e.g. name=rule1,rule=Mask secrets)
	OutputRule []string `json:"output-rule,omitempty"`
	// The length of the password to be generated
	PasswordLength *string `json:"password-length,omitempty"`
	// Rotate this secret after it is unlocked
	RotateOnUnlock *string `json:"rotate-on-unlock,omitempty"`
	// rotated-username password (relevant only for rotator-type=password)
	RotatedPassword *string `json:"rotated-password,omitempty"`
	// username to be rotated, if selected use-self-creds at rotator-creds-type, this username will try to rotate it's own password, if use-target-creds is selected, target credentials will be use to rotate the rotated-password (relevant only for rotator-type=password)
	RotatedUsername *string `json:"rotated-username,omitempty"`
	// How many days before the rotation of the item would you like to be notified
	RotationEventIn []string `json:"rotation-event-in,omitempty"`
	RotationHour *int32 `json:"rotation-hour,omitempty"`
	RotationInterval *string `json:"rotation-interval,omitempty"`
	// The rotator type. options: [target/password]
	RotatorType string `json:"rotator-type"`
	// If set, dry-run will be skipped
	SkipDryRun *string `json:"skip_dry_run,omitempty"`
	// Add tags attached to this object
	Tags []string `json:"tags,omitempty"`
	// The target name to associate
	TargetName string `json:"target-name"`
	// Authentication token (see `/auth` and `/configure`)
	Token *string `json:"token,omitempty"`
	// The universal identity token, Required only for universal_identity authentication
	UidToken *string `json:"uid-token,omitempty"`
	// Specifies whether the generated temporary password must contain at least one uppercase character from the ISO basic Latin alphabet (A to Z). [true/false]
	UseCapitalLetters *string `json:"use-capital-letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one lowercase character from the ISO basic Latin alphabet (a to z). [true/false]
	UseLowerLetters *string `json:"use-lower-letters,omitempty"`
	// Specifies whether the generated temporary password must contain at least one numeric character (0 to 9). [true/false]
	UseNumbers *string `json:"use-numbers,omitempty"`
	UseSpecialCharacters *string `json:"use-special-characters,omitempty"`
}

type _RotatedSecretCreateHanadb RotatedSecretCreateHanadb

// NewRotatedSecretCreateHanadb instantiates a new RotatedSecretCreateHanadb object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotatedSecretCreateHanadb(name string, rotatorType string, targetName string) *RotatedSecretCreateHanadb {
	this := RotatedSecretCreateHanadb{}
	var authenticationCredentials string = "use-user-creds"
	this.AuthenticationCredentials = &authenticationCredentials
	var json bool = false
	this.Json = &json
	this.Name = name
	this.RotatorType = rotatorType
	this.TargetName = targetName
	return &this
}

// NewRotatedSecretCreateHanadbWithDefaults instantiates a new RotatedSecretCreateHanadb object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotatedSecretCreateHanadbWithDefaults() *RotatedSecretCreateHanadb {
	this := RotatedSecretCreateHanadb{}
	var authenticationCredentials string = "use-user-creds"
	this.AuthenticationCredentials = &authenticationCredentials
	var json bool = false
	this.Json = &json
	return &this
}

// GetAraEnabled returns the AraEnabled field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetAraEnabled() bool {
	if o == nil || IsNil(o.AraEnabled) {
		var ret bool
		return ret
	}
	return *o.AraEnabled
}

// GetAraEnabledOk returns a tuple with the AraEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetAraEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.AraEnabled) {
		return nil, false
	}
	return o.AraEnabled, true
}

// HasAraEnabled returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasAraEnabled() bool {
	if o != nil && !IsNil(o.AraEnabled) {
		return true
	}

	return false
}

// SetAraEnabled gets a reference to the given bool and assigns it to the AraEnabled field.
func (o *RotatedSecretCreateHanadb) SetAraEnabled(v bool) {
	o.AraEnabled = &v
}

// GetAuthenticationCredentials returns the AuthenticationCredentials field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetAuthenticationCredentials() string {
	if o == nil || IsNil(o.AuthenticationCredentials) {
		var ret string
		return ret
	}
	return *o.AuthenticationCredentials
}

// GetAuthenticationCredentialsOk returns a tuple with the AuthenticationCredentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetAuthenticationCredentialsOk() (*string, bool) {
	if o == nil || IsNil(o.AuthenticationCredentials) {
		return nil, false
	}
	return o.AuthenticationCredentials, true
}

// HasAuthenticationCredentials returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasAuthenticationCredentials() bool {
	if o != nil && !IsNil(o.AuthenticationCredentials) {
		return true
	}

	return false
}

// SetAuthenticationCredentials gets a reference to the given string and assigns it to the AuthenticationCredentials field.
func (o *RotatedSecretCreateHanadb) SetAuthenticationCredentials(v string) {
	o.AuthenticationCredentials = &v
}

// GetAutoRotate returns the AutoRotate field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetAutoRotate() string {
	if o == nil || IsNil(o.AutoRotate) {
		var ret string
		return ret
	}
	return *o.AutoRotate
}

// GetAutoRotateOk returns a tuple with the AutoRotate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetAutoRotateOk() (*string, bool) {
	if o == nil || IsNil(o.AutoRotate) {
		return nil, false
	}
	return o.AutoRotate, true
}

// HasAutoRotate returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasAutoRotate() bool {
	if o != nil && !IsNil(o.AutoRotate) {
		return true
	}

	return false
}

// SetAutoRotate gets a reference to the given string and assigns it to the AutoRotate field.
func (o *RotatedSecretCreateHanadb) SetAutoRotate(v string) {
	o.AutoRotate = &v
}

// GetDeleteProtection returns the DeleteProtection field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetDeleteProtection() string {
	if o == nil || IsNil(o.DeleteProtection) {
		var ret string
		return ret
	}
	return *o.DeleteProtection
}

// GetDeleteProtectionOk returns a tuple with the DeleteProtection field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetDeleteProtectionOk() (*string, bool) {
	if o == nil || IsNil(o.DeleteProtection) {
		return nil, false
	}
	return o.DeleteProtection, true
}

// HasDeleteProtection returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasDeleteProtection() bool {
	if o != nil && !IsNil(o.DeleteProtection) {
		return true
	}

	return false
}

// SetDeleteProtection gets a reference to the given string and assigns it to the DeleteProtection field.
func (o *RotatedSecretCreateHanadb) SetDeleteProtection(v string) {
	o.DeleteProtection = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RotatedSecretCreateHanadb) SetDescription(v string) {
	o.Description = &v
}

// GetEnableAgenticRuntimeAuthority returns the EnableAgenticRuntimeAuthority field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetEnableAgenticRuntimeAuthority() bool {
	if o == nil || IsNil(o.EnableAgenticRuntimeAuthority) {
		var ret bool
		return ret
	}
	return *o.EnableAgenticRuntimeAuthority
}

// GetEnableAgenticRuntimeAuthorityOk returns a tuple with the EnableAgenticRuntimeAuthority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetEnableAgenticRuntimeAuthorityOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableAgenticRuntimeAuthority) {
		return nil, false
	}
	return o.EnableAgenticRuntimeAuthority, true
}

// HasEnableAgenticRuntimeAuthority returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasEnableAgenticRuntimeAuthority() bool {
	if o != nil && !IsNil(o.EnableAgenticRuntimeAuthority) {
		return true
	}

	return false
}

// SetEnableAgenticRuntimeAuthority gets a reference to the given bool and assigns it to the EnableAgenticRuntimeAuthority field.
func (o *RotatedSecretCreateHanadb) SetEnableAgenticRuntimeAuthority(v bool) {
	o.EnableAgenticRuntimeAuthority = &v
}

// GetEnableAiQuorum returns the EnableAiQuorum field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetEnableAiQuorum() bool {
	if o == nil || IsNil(o.EnableAiQuorum) {
		var ret bool
		return ret
	}
	return *o.EnableAiQuorum
}

// GetEnableAiQuorumOk returns a tuple with the EnableAiQuorum field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetEnableAiQuorumOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableAiQuorum) {
		return nil, false
	}
	return o.EnableAiQuorum, true
}

// HasEnableAiQuorum returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasEnableAiQuorum() bool {
	if o != nil && !IsNil(o.EnableAiQuorum) {
		return true
	}

	return false
}

// SetEnableAiQuorum gets a reference to the given bool and assigns it to the EnableAiQuorum field.
func (o *RotatedSecretCreateHanadb) SetEnableAiQuorum(v bool) {
	o.EnableAiQuorum = &v
}

// GetInputRule returns the InputRule field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetInputRule() []string {
	if o == nil || IsNil(o.InputRule) {
		var ret []string
		return ret
	}
	return o.InputRule
}

// GetInputRuleOk returns a tuple with the InputRule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetInputRuleOk() ([]string, bool) {
	if o == nil || IsNil(o.InputRule) {
		return nil, false
	}
	return o.InputRule, true
}

// HasInputRule returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasInputRule() bool {
	if o != nil && !IsNil(o.InputRule) {
		return true
	}

	return false
}

// SetInputRule gets a reference to the given []string and assigns it to the InputRule field.
func (o *RotatedSecretCreateHanadb) SetInputRule(v []string) {
	o.InputRule = v
}

// GetItemCustomFields returns the ItemCustomFields field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetItemCustomFields() map[string]string {
	if o == nil || IsNil(o.ItemCustomFields) {
		var ret map[string]string
		return ret
	}
	return *o.ItemCustomFields
}

// GetItemCustomFieldsOk returns a tuple with the ItemCustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetItemCustomFieldsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.ItemCustomFields) {
		return nil, false
	}
	return o.ItemCustomFields, true
}

// HasItemCustomFields returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasItemCustomFields() bool {
	if o != nil && !IsNil(o.ItemCustomFields) {
		return true
	}

	return false
}

// SetItemCustomFields gets a reference to the given map[string]string and assigns it to the ItemCustomFields field.
func (o *RotatedSecretCreateHanadb) SetItemCustomFields(v map[string]string) {
	o.ItemCustomFields = &v
}

// GetJson returns the Json field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetJson() bool {
	if o == nil || IsNil(o.Json) {
		var ret bool
		return ret
	}
	return *o.Json
}

// GetJsonOk returns a tuple with the Json field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetJsonOk() (*bool, bool) {
	if o == nil || IsNil(o.Json) {
		return nil, false
	}
	return o.Json, true
}

// HasJson returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasJson() bool {
	if o != nil && !IsNil(o.Json) {
		return true
	}

	return false
}

// SetJson gets a reference to the given bool and assigns it to the Json field.
func (o *RotatedSecretCreateHanadb) SetJson(v bool) {
	o.Json = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *RotatedSecretCreateHanadb) SetKey(v string) {
	o.Key = &v
}

// GetLockOnRead returns the LockOnRead field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetLockOnRead() string {
	if o == nil || IsNil(o.LockOnRead) {
		var ret string
		return ret
	}
	return *o.LockOnRead
}

// GetLockOnReadOk returns a tuple with the LockOnRead field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetLockOnReadOk() (*string, bool) {
	if o == nil || IsNil(o.LockOnRead) {
		return nil, false
	}
	return o.LockOnRead, true
}

// HasLockOnRead returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasLockOnRead() bool {
	if o != nil && !IsNil(o.LockOnRead) {
		return true
	}

	return false
}

// SetLockOnRead gets a reference to the given string and assigns it to the LockOnRead field.
func (o *RotatedSecretCreateHanadb) SetLockOnRead(v string) {
	o.LockOnRead = &v
}

// GetLockTtl returns the LockTtl field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetLockTtl() string {
	if o == nil || IsNil(o.LockTtl) {
		var ret string
		return ret
	}
	return *o.LockTtl
}

// GetLockTtlOk returns a tuple with the LockTtl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetLockTtlOk() (*string, bool) {
	if o == nil || IsNil(o.LockTtl) {
		return nil, false
	}
	return o.LockTtl, true
}

// HasLockTtl returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasLockTtl() bool {
	if o != nil && !IsNil(o.LockTtl) {
		return true
	}

	return false
}

// SetLockTtl gets a reference to the given string and assigns it to the LockTtl field.
func (o *RotatedSecretCreateHanadb) SetLockTtl(v string) {
	o.LockTtl = &v
}

// GetMaxVersions returns the MaxVersions field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetMaxVersions() string {
	if o == nil || IsNil(o.MaxVersions) {
		var ret string
		return ret
	}
	return *o.MaxVersions
}

// GetMaxVersionsOk returns a tuple with the MaxVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetMaxVersionsOk() (*string, bool) {
	if o == nil || IsNil(o.MaxVersions) {
		return nil, false
	}
	return o.MaxVersions, true
}

// HasMaxVersions returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasMaxVersions() bool {
	if o != nil && !IsNil(o.MaxVersions) {
		return true
	}

	return false
}

// SetMaxVersions gets a reference to the given string and assigns it to the MaxVersions field.
func (o *RotatedSecretCreateHanadb) SetMaxVersions(v string) {
	o.MaxVersions = &v
}

// GetName returns the Name field value
func (o *RotatedSecretCreateHanadb) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RotatedSecretCreateHanadb) SetName(v string) {
	o.Name = v
}

// GetOutputRule returns the OutputRule field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetOutputRule() []string {
	if o == nil || IsNil(o.OutputRule) {
		var ret []string
		return ret
	}
	return o.OutputRule
}

// GetOutputRuleOk returns a tuple with the OutputRule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetOutputRuleOk() ([]string, bool) {
	if o == nil || IsNil(o.OutputRule) {
		return nil, false
	}
	return o.OutputRule, true
}

// HasOutputRule returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasOutputRule() bool {
	if o != nil && !IsNil(o.OutputRule) {
		return true
	}

	return false
}

// SetOutputRule gets a reference to the given []string and assigns it to the OutputRule field.
func (o *RotatedSecretCreateHanadb) SetOutputRule(v []string) {
	o.OutputRule = v
}

// GetPasswordLength returns the PasswordLength field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetPasswordLength() string {
	if o == nil || IsNil(o.PasswordLength) {
		var ret string
		return ret
	}
	return *o.PasswordLength
}

// GetPasswordLengthOk returns a tuple with the PasswordLength field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetPasswordLengthOk() (*string, bool) {
	if o == nil || IsNil(o.PasswordLength) {
		return nil, false
	}
	return o.PasswordLength, true
}

// HasPasswordLength returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasPasswordLength() bool {
	if o != nil && !IsNil(o.PasswordLength) {
		return true
	}

	return false
}

// SetPasswordLength gets a reference to the given string and assigns it to the PasswordLength field.
func (o *RotatedSecretCreateHanadb) SetPasswordLength(v string) {
	o.PasswordLength = &v
}

// GetRotateOnUnlock returns the RotateOnUnlock field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetRotateOnUnlock() string {
	if o == nil || IsNil(o.RotateOnUnlock) {
		var ret string
		return ret
	}
	return *o.RotateOnUnlock
}

// GetRotateOnUnlockOk returns a tuple with the RotateOnUnlock field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetRotateOnUnlockOk() (*string, bool) {
	if o == nil || IsNil(o.RotateOnUnlock) {
		return nil, false
	}
	return o.RotateOnUnlock, true
}

// HasRotateOnUnlock returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasRotateOnUnlock() bool {
	if o != nil && !IsNil(o.RotateOnUnlock) {
		return true
	}

	return false
}

// SetRotateOnUnlock gets a reference to the given string and assigns it to the RotateOnUnlock field.
func (o *RotatedSecretCreateHanadb) SetRotateOnUnlock(v string) {
	o.RotateOnUnlock = &v
}

// GetRotatedPassword returns the RotatedPassword field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetRotatedPassword() string {
	if o == nil || IsNil(o.RotatedPassword) {
		var ret string
		return ret
	}
	return *o.RotatedPassword
}

// GetRotatedPasswordOk returns a tuple with the RotatedPassword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetRotatedPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.RotatedPassword) {
		return nil, false
	}
	return o.RotatedPassword, true
}

// HasRotatedPassword returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasRotatedPassword() bool {
	if o != nil && !IsNil(o.RotatedPassword) {
		return true
	}

	return false
}

// SetRotatedPassword gets a reference to the given string and assigns it to the RotatedPassword field.
func (o *RotatedSecretCreateHanadb) SetRotatedPassword(v string) {
	o.RotatedPassword = &v
}

// GetRotatedUsername returns the RotatedUsername field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetRotatedUsername() string {
	if o == nil || IsNil(o.RotatedUsername) {
		var ret string
		return ret
	}
	return *o.RotatedUsername
}

// GetRotatedUsernameOk returns a tuple with the RotatedUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetRotatedUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.RotatedUsername) {
		return nil, false
	}
	return o.RotatedUsername, true
}

// HasRotatedUsername returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasRotatedUsername() bool {
	if o != nil && !IsNil(o.RotatedUsername) {
		return true
	}

	return false
}

// SetRotatedUsername gets a reference to the given string and assigns it to the RotatedUsername field.
func (o *RotatedSecretCreateHanadb) SetRotatedUsername(v string) {
	o.RotatedUsername = &v
}

// GetRotationEventIn returns the RotationEventIn field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetRotationEventIn() []string {
	if o == nil || IsNil(o.RotationEventIn) {
		var ret []string
		return ret
	}
	return o.RotationEventIn
}

// GetRotationEventInOk returns a tuple with the RotationEventIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetRotationEventInOk() ([]string, bool) {
	if o == nil || IsNil(o.RotationEventIn) {
		return nil, false
	}
	return o.RotationEventIn, true
}

// HasRotationEventIn returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasRotationEventIn() bool {
	if o != nil && !IsNil(o.RotationEventIn) {
		return true
	}

	return false
}

// SetRotationEventIn gets a reference to the given []string and assigns it to the RotationEventIn field.
func (o *RotatedSecretCreateHanadb) SetRotationEventIn(v []string) {
	o.RotationEventIn = v
}

// GetRotationHour returns the RotationHour field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetRotationHour() int32 {
	if o == nil || IsNil(o.RotationHour) {
		var ret int32
		return ret
	}
	return *o.RotationHour
}

// GetRotationHourOk returns a tuple with the RotationHour field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetRotationHourOk() (*int32, bool) {
	if o == nil || IsNil(o.RotationHour) {
		return nil, false
	}
	return o.RotationHour, true
}

// HasRotationHour returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasRotationHour() bool {
	if o != nil && !IsNil(o.RotationHour) {
		return true
	}

	return false
}

// SetRotationHour gets a reference to the given int32 and assigns it to the RotationHour field.
func (o *RotatedSecretCreateHanadb) SetRotationHour(v int32) {
	o.RotationHour = &v
}

// GetRotationInterval returns the RotationInterval field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetRotationInterval() string {
	if o == nil || IsNil(o.RotationInterval) {
		var ret string
		return ret
	}
	return *o.RotationInterval
}

// GetRotationIntervalOk returns a tuple with the RotationInterval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetRotationIntervalOk() (*string, bool) {
	if o == nil || IsNil(o.RotationInterval) {
		return nil, false
	}
	return o.RotationInterval, true
}

// HasRotationInterval returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasRotationInterval() bool {
	if o != nil && !IsNil(o.RotationInterval) {
		return true
	}

	return false
}

// SetRotationInterval gets a reference to the given string and assigns it to the RotationInterval field.
func (o *RotatedSecretCreateHanadb) SetRotationInterval(v string) {
	o.RotationInterval = &v
}

// GetRotatorType returns the RotatorType field value
func (o *RotatedSecretCreateHanadb) GetRotatorType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RotatorType
}

// GetRotatorTypeOk returns a tuple with the RotatorType field value
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetRotatorTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RotatorType, true
}

// SetRotatorType sets field value
func (o *RotatedSecretCreateHanadb) SetRotatorType(v string) {
	o.RotatorType = v
}

// GetSkipDryRun returns the SkipDryRun field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetSkipDryRun() string {
	if o == nil || IsNil(o.SkipDryRun) {
		var ret string
		return ret
	}
	return *o.SkipDryRun
}

// GetSkipDryRunOk returns a tuple with the SkipDryRun field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetSkipDryRunOk() (*string, bool) {
	if o == nil || IsNil(o.SkipDryRun) {
		return nil, false
	}
	return o.SkipDryRun, true
}

// HasSkipDryRun returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasSkipDryRun() bool {
	if o != nil && !IsNil(o.SkipDryRun) {
		return true
	}

	return false
}

// SetSkipDryRun gets a reference to the given string and assigns it to the SkipDryRun field.
func (o *RotatedSecretCreateHanadb) SetSkipDryRun(v string) {
	o.SkipDryRun = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *RotatedSecretCreateHanadb) SetTags(v []string) {
	o.Tags = v
}

// GetTargetName returns the TargetName field value
func (o *RotatedSecretCreateHanadb) GetTargetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TargetName
}

// GetTargetNameOk returns a tuple with the TargetName field value
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetTargetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TargetName, true
}

// SetTargetName sets field value
func (o *RotatedSecretCreateHanadb) SetTargetName(v string) {
	o.TargetName = v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *RotatedSecretCreateHanadb) SetToken(v string) {
	o.Token = &v
}

// GetUidToken returns the UidToken field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetUidToken() string {
	if o == nil || IsNil(o.UidToken) {
		var ret string
		return ret
	}
	return *o.UidToken
}

// GetUidTokenOk returns a tuple with the UidToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetUidTokenOk() (*string, bool) {
	if o == nil || IsNil(o.UidToken) {
		return nil, false
	}
	return o.UidToken, true
}

// HasUidToken returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasUidToken() bool {
	if o != nil && !IsNil(o.UidToken) {
		return true
	}

	return false
}

// SetUidToken gets a reference to the given string and assigns it to the UidToken field.
func (o *RotatedSecretCreateHanadb) SetUidToken(v string) {
	o.UidToken = &v
}

// GetUseCapitalLetters returns the UseCapitalLetters field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetUseCapitalLetters() string {
	if o == nil || IsNil(o.UseCapitalLetters) {
		var ret string
		return ret
	}
	return *o.UseCapitalLetters
}

// GetUseCapitalLettersOk returns a tuple with the UseCapitalLetters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetUseCapitalLettersOk() (*string, bool) {
	if o == nil || IsNil(o.UseCapitalLetters) {
		return nil, false
	}
	return o.UseCapitalLetters, true
}

// HasUseCapitalLetters returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasUseCapitalLetters() bool {
	if o != nil && !IsNil(o.UseCapitalLetters) {
		return true
	}

	return false
}

// SetUseCapitalLetters gets a reference to the given string and assigns it to the UseCapitalLetters field.
func (o *RotatedSecretCreateHanadb) SetUseCapitalLetters(v string) {
	o.UseCapitalLetters = &v
}

// GetUseLowerLetters returns the UseLowerLetters field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetUseLowerLetters() string {
	if o == nil || IsNil(o.UseLowerLetters) {
		var ret string
		return ret
	}
	return *o.UseLowerLetters
}

// GetUseLowerLettersOk returns a tuple with the UseLowerLetters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetUseLowerLettersOk() (*string, bool) {
	if o == nil || IsNil(o.UseLowerLetters) {
		return nil, false
	}
	return o.UseLowerLetters, true
}

// HasUseLowerLetters returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasUseLowerLetters() bool {
	if o != nil && !IsNil(o.UseLowerLetters) {
		return true
	}

	return false
}

// SetUseLowerLetters gets a reference to the given string and assigns it to the UseLowerLetters field.
func (o *RotatedSecretCreateHanadb) SetUseLowerLetters(v string) {
	o.UseLowerLetters = &v
}

// GetUseNumbers returns the UseNumbers field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetUseNumbers() string {
	if o == nil || IsNil(o.UseNumbers) {
		var ret string
		return ret
	}
	return *o.UseNumbers
}

// GetUseNumbersOk returns a tuple with the UseNumbers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetUseNumbersOk() (*string, bool) {
	if o == nil || IsNil(o.UseNumbers) {
		return nil, false
	}
	return o.UseNumbers, true
}

// HasUseNumbers returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasUseNumbers() bool {
	if o != nil && !IsNil(o.UseNumbers) {
		return true
	}

	return false
}

// SetUseNumbers gets a reference to the given string and assigns it to the UseNumbers field.
func (o *RotatedSecretCreateHanadb) SetUseNumbers(v string) {
	o.UseNumbers = &v
}

// GetUseSpecialCharacters returns the UseSpecialCharacters field value if set, zero value otherwise.
func (o *RotatedSecretCreateHanadb) GetUseSpecialCharacters() string {
	if o == nil || IsNil(o.UseSpecialCharacters) {
		var ret string
		return ret
	}
	return *o.UseSpecialCharacters
}

// GetUseSpecialCharactersOk returns a tuple with the UseSpecialCharacters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RotatedSecretCreateHanadb) GetUseSpecialCharactersOk() (*string, bool) {
	if o == nil || IsNil(o.UseSpecialCharacters) {
		return nil, false
	}
	return o.UseSpecialCharacters, true
}

// HasUseSpecialCharacters returns a boolean if a field has been set.
func (o *RotatedSecretCreateHanadb) HasUseSpecialCharacters() bool {
	if o != nil && !IsNil(o.UseSpecialCharacters) {
		return true
	}

	return false
}

// SetUseSpecialCharacters gets a reference to the given string and assigns it to the UseSpecialCharacters field.
func (o *RotatedSecretCreateHanadb) SetUseSpecialCharacters(v string) {
	o.UseSpecialCharacters = &v
}

func (o RotatedSecretCreateHanadb) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RotatedSecretCreateHanadb) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AraEnabled) {
		toSerialize["ara-enabled"] = o.AraEnabled
	}
	if !IsNil(o.AuthenticationCredentials) {
		toSerialize["authentication-credentials"] = o.AuthenticationCredentials
	}
	if !IsNil(o.AutoRotate) {
		toSerialize["auto-rotate"] = o.AutoRotate
	}
	if !IsNil(o.DeleteProtection) {
		toSerialize["delete_protection"] = o.DeleteProtection
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.EnableAgenticRuntimeAuthority) {
		toSerialize["enable-agentic-runtime-authority"] = o.EnableAgenticRuntimeAuthority
	}
	if !IsNil(o.EnableAiQuorum) {
		toSerialize["enable-ai-quorum"] = o.EnableAiQuorum
	}
	if !IsNil(o.InputRule) {
		toSerialize["input-rule"] = o.InputRule
	}
	if !IsNil(o.ItemCustomFields) {
		toSerialize["item-custom-fields"] = o.ItemCustomFields
	}
	if !IsNil(o.Json) {
		toSerialize["json"] = o.Json
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.LockOnRead) {
		toSerialize["lock-on-read"] = o.LockOnRead
	}
	if !IsNil(o.LockTtl) {
		toSerialize["lock-ttl"] = o.LockTtl
	}
	if !IsNil(o.MaxVersions) {
		toSerialize["max-versions"] = o.MaxVersions
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.OutputRule) {
		toSerialize["output-rule"] = o.OutputRule
	}
	if !IsNil(o.PasswordLength) {
		toSerialize["password-length"] = o.PasswordLength
	}
	if !IsNil(o.RotateOnUnlock) {
		toSerialize["rotate-on-unlock"] = o.RotateOnUnlock
	}
	if !IsNil(o.RotatedPassword) {
		toSerialize["rotated-password"] = o.RotatedPassword
	}
	if !IsNil(o.RotatedUsername) {
		toSerialize["rotated-username"] = o.RotatedUsername
	}
	if !IsNil(o.RotationEventIn) {
		toSerialize["rotation-event-in"] = o.RotationEventIn
	}
	if !IsNil(o.RotationHour) {
		toSerialize["rotation-hour"] = o.RotationHour
	}
	if !IsNil(o.RotationInterval) {
		toSerialize["rotation-interval"] = o.RotationInterval
	}
	toSerialize["rotator-type"] = o.RotatorType
	if !IsNil(o.SkipDryRun) {
		toSerialize["skip_dry_run"] = o.SkipDryRun
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	toSerialize["target-name"] = o.TargetName
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.UidToken) {
		toSerialize["uid-token"] = o.UidToken
	}
	if !IsNil(o.UseCapitalLetters) {
		toSerialize["use-capital-letters"] = o.UseCapitalLetters
	}
	if !IsNil(o.UseLowerLetters) {
		toSerialize["use-lower-letters"] = o.UseLowerLetters
	}
	if !IsNil(o.UseNumbers) {
		toSerialize["use-numbers"] = o.UseNumbers
	}
	if !IsNil(o.UseSpecialCharacters) {
		toSerialize["use-special-characters"] = o.UseSpecialCharacters
	}
	return toSerialize, nil
}

func (o *RotatedSecretCreateHanadb) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"rotator-type",
		"target-name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRotatedSecretCreateHanadb := _RotatedSecretCreateHanadb{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRotatedSecretCreateHanadb)

	if err != nil {
		return err
	}

	*o = RotatedSecretCreateHanadb(varRotatedSecretCreateHanadb)

	return err
}

type NullableRotatedSecretCreateHanadb struct {
	value *RotatedSecretCreateHanadb
	isSet bool
}

func (v NullableRotatedSecretCreateHanadb) Get() *RotatedSecretCreateHanadb {
	return v.value
}

func (v *NullableRotatedSecretCreateHanadb) Set(val *RotatedSecretCreateHanadb) {
	v.value = val
	v.isSet = true
}

func (v NullableRotatedSecretCreateHanadb) IsSet() bool {
	return v.isSet
}

func (v *NullableRotatedSecretCreateHanadb) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotatedSecretCreateHanadb(val *RotatedSecretCreateHanadb) *NullableRotatedSecretCreateHanadb {
	return &NullableRotatedSecretCreateHanadb{value: val, isSet: true}
}

func (v NullableRotatedSecretCreateHanadb) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotatedSecretCreateHanadb) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


