/*
Akeyless API

The purpose of this application is to provide access to Akeyless API.

API version: 3.0
Contact: support@akeyless.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package akeyless

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TargetCreateLetsEncrypt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TargetCreateLetsEncrypt{}

// TargetCreateLetsEncrypt targetCreateLetsEncrypt is a command that creates a new Let's Encrypt target
type TargetCreateLetsEncrypt struct {
	AcmeChallenge *string `json:"acme-challenge,omitempty"`
	// Description of the object
	Description *string `json:"description,omitempty"`
	// Name of existing cloud target for DNS credentials. Required when acme-challenge=dns. Supported: AWS, Azure, GCP targets
	DnsTargetCreds *string `json:"dns-target-creds,omitempty"`
	// Email address for ACME account registration
	Email *string `json:"email,omitempty"`
	// GCP Cloud DNS: Project ID. Optional - can be derived from service account
	GcpProject *string `json:"gcp-project,omitempty"`
	// AWS Route53 hosted zone ID. Required when dns-target-creds points to AWS target
	HostedZone *string `json:"hosted-zone,omitempty"`
	// Set output format to JSON
	Json *bool `json:"json,omitempty"`
	// The name of a key that used to encrypt the target secret value (if empty, the account default protectionKey key will be used)
	Key *string `json:"key,omitempty"`
	LetsEncryptUrl *string `json:"lets-encrypt-url,omitempty"`
	// Set the maximum number of versions, limited by the account settings defaults.
	MaxVersions *string `json:"max-versions,omitempty"`
	// Target name
	Name string `json:"name"`
	// Azure resource group name. Required when dns-target-creds points to Azure target
	ResourceGroup *string `json:"resource-group,omitempty"`
	Timeout *string `json:"timeout,omitempty"`
	// Authentication token (see `/auth` and `/configure`)
	Token *string `json:"token,omitempty"`
	// The universal identity token, Required only for universal_identity authentication
	UidToken *string `json:"uid-token,omitempty"`
}

type _TargetCreateLetsEncrypt TargetCreateLetsEncrypt

// NewTargetCreateLetsEncrypt instantiates a new TargetCreateLetsEncrypt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTargetCreateLetsEncrypt(name string) *TargetCreateLetsEncrypt {
	this := TargetCreateLetsEncrypt{}
	var acmeChallenge string = "http"
	this.AcmeChallenge = &acmeChallenge
	var json bool = false
	this.Json = &json
	var letsEncryptUrl string = "production"
	this.LetsEncryptUrl = &letsEncryptUrl
	this.Name = name
	var timeout string = "5m"
	this.Timeout = &timeout
	return &this
}

// NewTargetCreateLetsEncryptWithDefaults instantiates a new TargetCreateLetsEncrypt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTargetCreateLetsEncryptWithDefaults() *TargetCreateLetsEncrypt {
	this := TargetCreateLetsEncrypt{}
	var acmeChallenge string = "http"
	this.AcmeChallenge = &acmeChallenge
	var json bool = false
	this.Json = &json
	var letsEncryptUrl string = "production"
	this.LetsEncryptUrl = &letsEncryptUrl
	var timeout string = "5m"
	this.Timeout = &timeout
	return &this
}

// GetAcmeChallenge returns the AcmeChallenge field value if set, zero value otherwise.
func (o *TargetCreateLetsEncrypt) GetAcmeChallenge() string {
	if o == nil || IsNil(o.AcmeChallenge) {
		var ret string
		return ret
	}
	return *o.AcmeChallenge
}

// GetAcmeChallengeOk returns a tuple with the AcmeChallenge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TargetCreateLetsEncrypt) GetAcmeChallengeOk() (*string, bool) {
	if o == nil || IsNil(o.AcmeChallenge) {
		return nil, false
	}
	return o.AcmeChallenge, true
}

// HasAcmeChallenge returns a boolean if a field has been set.
func (o *TargetCreateLetsEncrypt) HasAcmeChallenge() bool {
	if o != nil && !IsNil(o.AcmeChallenge) {
		return true
	}

	return false
}

// SetAcmeChallenge gets a reference to the given string and assigns it to the AcmeChallenge field.
func (o *TargetCreateLetsEncrypt) SetAcmeChallenge(v string) {
	o.AcmeChallenge = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *TargetCreateLetsEncrypt) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TargetCreateLetsEncrypt) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *TargetCreateLetsEncrypt) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *TargetCreateLetsEncrypt) SetDescription(v string) {
	o.Description = &v
}

// GetDnsTargetCreds returns the DnsTargetCreds field value if set, zero value otherwise.
func (o *TargetCreateLetsEncrypt) GetDnsTargetCreds() string {
	if o == nil || IsNil(o.DnsTargetCreds) {
		var ret string
		return ret
	}
	return *o.DnsTargetCreds
}

// GetDnsTargetCredsOk returns a tuple with the DnsTargetCreds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TargetCreateLetsEncrypt) GetDnsTargetCredsOk() (*string, bool) {
	if o == nil || IsNil(o.DnsTargetCreds) {
		return nil, false
	}
	return o.DnsTargetCreds, true
}

// HasDnsTargetCreds returns a boolean if a field has been set.
func (o *TargetCreateLetsEncrypt) HasDnsTargetCreds() bool {
	if o != nil && !IsNil(o.DnsTargetCreds) {
		return true
	}

	return false
}

// SetDnsTargetCreds gets a reference to the given string and assigns it to the DnsTargetCreds field.
func (o *TargetCreateLetsEncrypt) SetDnsTargetCreds(v string) {
	o.DnsTargetCreds = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *TargetCreateLetsEncrypt) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TargetCreateLetsEncrypt) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *TargetCreateLetsEncrypt) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *TargetCreateLetsEncrypt) SetEmail(v string) {
	o.Email = &v
}

// GetGcpProject returns the GcpProject field value if set, zero value otherwise.
func (o *TargetCreateLetsEncrypt) GetGcpProject() string {
	if o == nil || IsNil(o.GcpProject) {
		var ret string
		return ret
	}
	return *o.GcpProject
}

// GetGcpProjectOk returns a tuple with the GcpProject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TargetCreateLetsEncrypt) GetGcpProjectOk() (*string, bool) {
	if o == nil || IsNil(o.GcpProject) {
		return nil, false
	}
	return o.GcpProject, true
}

// HasGcpProject returns a boolean if a field has been set.
func (o *TargetCreateLetsEncrypt) HasGcpProject() bool {
	if o != nil && !IsNil(o.GcpProject) {
		return true
	}

	return false
}

// SetGcpProject gets a reference to the given string and assigns it to the GcpProject field.
func (o *TargetCreateLetsEncrypt) SetGcpProject(v string) {
	o.GcpProject = &v
}

// GetHostedZone returns the HostedZone field value if set, zero value otherwise.
func (o *TargetCreateLetsEncrypt) GetHostedZone() string {
	if o == nil || IsNil(o.HostedZone) {
		var ret string
		return ret
	}
	return *o.HostedZone
}

// GetHostedZoneOk returns a tuple with the HostedZone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TargetCreateLetsEncrypt) GetHostedZoneOk() (*string, bool) {
	if o == nil || IsNil(o.HostedZone) {
		return nil, false
	}
	return o.HostedZone, true
}

// HasHostedZone returns a boolean if a field has been set.
func (o *TargetCreateLetsEncrypt) HasHostedZone() bool {
	if o != nil && !IsNil(o.HostedZone) {
		return true
	}

	return false
}

// SetHostedZone gets a reference to the given string and assigns it to the HostedZone field.
func (o *TargetCreateLetsEncrypt) SetHostedZone(v string) {
	o.HostedZone = &v
}

// GetJson returns the Json field value if set, zero value otherwise.
func (o *TargetCreateLetsEncrypt) GetJson() bool {
	if o == nil || IsNil(o.Json) {
		var ret bool
		return ret
	}
	return *o.Json
}

// GetJsonOk returns a tuple with the Json field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TargetCreateLetsEncrypt) GetJsonOk() (*bool, bool) {
	if o == nil || IsNil(o.Json) {
		return nil, false
	}
	return o.Json, true
}

// HasJson returns a boolean if a field has been set.
func (o *TargetCreateLetsEncrypt) HasJson() bool {
	if o != nil && !IsNil(o.Json) {
		return true
	}

	return false
}

// SetJson gets a reference to the given bool and assigns it to the Json field.
func (o *TargetCreateLetsEncrypt) SetJson(v bool) {
	o.Json = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *TargetCreateLetsEncrypt) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TargetCreateLetsEncrypt) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *TargetCreateLetsEncrypt) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *TargetCreateLetsEncrypt) SetKey(v string) {
	o.Key = &v
}

// GetLetsEncryptUrl returns the LetsEncryptUrl field value if set, zero value otherwise.
func (o *TargetCreateLetsEncrypt) GetLetsEncryptUrl() string {
	if o == nil || IsNil(o.LetsEncryptUrl) {
		var ret string
		return ret
	}
	return *o.LetsEncryptUrl
}

// GetLetsEncryptUrlOk returns a tuple with the LetsEncryptUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TargetCreateLetsEncrypt) GetLetsEncryptUrlOk() (*string, bool) {
	if o == nil || IsNil(o.LetsEncryptUrl) {
		return nil, false
	}
	return o.LetsEncryptUrl, true
}

// HasLetsEncryptUrl returns a boolean if a field has been set.
func (o *TargetCreateLetsEncrypt) HasLetsEncryptUrl() bool {
	if o != nil && !IsNil(o.LetsEncryptUrl) {
		return true
	}

	return false
}

// SetLetsEncryptUrl gets a reference to the given string and assigns it to the LetsEncryptUrl field.
func (o *TargetCreateLetsEncrypt) SetLetsEncryptUrl(v string) {
	o.LetsEncryptUrl = &v
}

// GetMaxVersions returns the MaxVersions field value if set, zero value otherwise.
func (o *TargetCreateLetsEncrypt) GetMaxVersions() string {
	if o == nil || IsNil(o.MaxVersions) {
		var ret string
		return ret
	}
	return *o.MaxVersions
}

// GetMaxVersionsOk returns a tuple with the MaxVersions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TargetCreateLetsEncrypt) GetMaxVersionsOk() (*string, bool) {
	if o == nil || IsNil(o.MaxVersions) {
		return nil, false
	}
	return o.MaxVersions, true
}

// HasMaxVersions returns a boolean if a field has been set.
func (o *TargetCreateLetsEncrypt) HasMaxVersions() bool {
	if o != nil && !IsNil(o.MaxVersions) {
		return true
	}

	return false
}

// SetMaxVersions gets a reference to the given string and assigns it to the MaxVersions field.
func (o *TargetCreateLetsEncrypt) SetMaxVersions(v string) {
	o.MaxVersions = &v
}

// GetName returns the Name field value
func (o *TargetCreateLetsEncrypt) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *TargetCreateLetsEncrypt) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *TargetCreateLetsEncrypt) SetName(v string) {
	o.Name = v
}

// GetResourceGroup returns the ResourceGroup field value if set, zero value otherwise.
func (o *TargetCreateLetsEncrypt) GetResourceGroup() string {
	if o == nil || IsNil(o.ResourceGroup) {
		var ret string
		return ret
	}
	return *o.ResourceGroup
}

// GetResourceGroupOk returns a tuple with the ResourceGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TargetCreateLetsEncrypt) GetResourceGroupOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceGroup) {
		return nil, false
	}
	return o.ResourceGroup, true
}

// HasResourceGroup returns a boolean if a field has been set.
func (o *TargetCreateLetsEncrypt) HasResourceGroup() bool {
	if o != nil && !IsNil(o.ResourceGroup) {
		return true
	}

	return false
}

// SetResourceGroup gets a reference to the given string and assigns it to the ResourceGroup field.
func (o *TargetCreateLetsEncrypt) SetResourceGroup(v string) {
	o.ResourceGroup = &v
}

// GetTimeout returns the Timeout field value if set, zero value otherwise.
func (o *TargetCreateLetsEncrypt) GetTimeout() string {
	if o == nil || IsNil(o.Timeout) {
		var ret string
		return ret
	}
	return *o.Timeout
}

// GetTimeoutOk returns a tuple with the Timeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TargetCreateLetsEncrypt) GetTimeoutOk() (*string, bool) {
	if o == nil || IsNil(o.Timeout) {
		return nil, false
	}
	return o.Timeout, true
}

// HasTimeout returns a boolean if a field has been set.
func (o *TargetCreateLetsEncrypt) HasTimeout() bool {
	if o != nil && !IsNil(o.Timeout) {
		return true
	}

	return false
}

// SetTimeout gets a reference to the given string and assigns it to the Timeout field.
func (o *TargetCreateLetsEncrypt) SetTimeout(v string) {
	o.Timeout = &v
}

// GetToken returns the Token field value if set, zero value otherwise.
func (o *TargetCreateLetsEncrypt) GetToken() string {
	if o == nil || IsNil(o.Token) {
		var ret string
		return ret
	}
	return *o.Token
}

// GetTokenOk returns a tuple with the Token field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TargetCreateLetsEncrypt) GetTokenOk() (*string, bool) {
	if o == nil || IsNil(o.Token) {
		return nil, false
	}
	return o.Token, true
}

// HasToken returns a boolean if a field has been set.
func (o *TargetCreateLetsEncrypt) HasToken() bool {
	if o != nil && !IsNil(o.Token) {
		return true
	}

	return false
}

// SetToken gets a reference to the given string and assigns it to the Token field.
func (o *TargetCreateLetsEncrypt) SetToken(v string) {
	o.Token = &v
}

// GetUidToken returns the UidToken field value if set, zero value otherwise.
func (o *TargetCreateLetsEncrypt) GetUidToken() string {
	if o == nil || IsNil(o.UidToken) {
		var ret string
		return ret
	}
	return *o.UidToken
}

// GetUidTokenOk returns a tuple with the UidToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TargetCreateLetsEncrypt) GetUidTokenOk() (*string, bool) {
	if o == nil || IsNil(o.UidToken) {
		return nil, false
	}
	return o.UidToken, true
}

// HasUidToken returns a boolean if a field has been set.
func (o *TargetCreateLetsEncrypt) HasUidToken() bool {
	if o != nil && !IsNil(o.UidToken) {
		return true
	}

	return false
}

// SetUidToken gets a reference to the given string and assigns it to the UidToken field.
func (o *TargetCreateLetsEncrypt) SetUidToken(v string) {
	o.UidToken = &v
}

func (o TargetCreateLetsEncrypt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TargetCreateLetsEncrypt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AcmeChallenge) {
		toSerialize["acme-challenge"] = o.AcmeChallenge
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DnsTargetCreds) {
		toSerialize["dns-target-creds"] = o.DnsTargetCreds
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.GcpProject) {
		toSerialize["gcp-project"] = o.GcpProject
	}
	if !IsNil(o.HostedZone) {
		toSerialize["hosted-zone"] = o.HostedZone
	}
	if !IsNil(o.Json) {
		toSerialize["json"] = o.Json
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.LetsEncryptUrl) {
		toSerialize["lets-encrypt-url"] = o.LetsEncryptUrl
	}
	if !IsNil(o.MaxVersions) {
		toSerialize["max-versions"] = o.MaxVersions
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.ResourceGroup) {
		toSerialize["resource-group"] = o.ResourceGroup
	}
	if !IsNil(o.Timeout) {
		toSerialize["timeout"] = o.Timeout
	}
	if !IsNil(o.Token) {
		toSerialize["token"] = o.Token
	}
	if !IsNil(o.UidToken) {
		toSerialize["uid-token"] = o.UidToken
	}
	return toSerialize, nil
}

func (o *TargetCreateLetsEncrypt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTargetCreateLetsEncrypt := _TargetCreateLetsEncrypt{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTargetCreateLetsEncrypt)

	if err != nil {
		return err
	}

	*o = TargetCreateLetsEncrypt(varTargetCreateLetsEncrypt)

	return err
}

type NullableTargetCreateLetsEncrypt struct {
	value *TargetCreateLetsEncrypt
	isSet bool
}

func (v NullableTargetCreateLetsEncrypt) Get() *TargetCreateLetsEncrypt {
	return v.value
}

func (v *NullableTargetCreateLetsEncrypt) Set(val *TargetCreateLetsEncrypt) {
	v.value = val
	v.isSet = true
}

func (v NullableTargetCreateLetsEncrypt) IsSet() bool {
	return v.isSet
}

func (v *NullableTargetCreateLetsEncrypt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTargetCreateLetsEncrypt(val *TargetCreateLetsEncrypt) *NullableTargetCreateLetsEncrypt {
	return &NullableTargetCreateLetsEncrypt{value: val, isSet: true}
}

func (v NullableTargetCreateLetsEncrypt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTargetCreateLetsEncrypt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


